name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
  
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
  
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
  
      - name: Restore Packages
        working-directory: DetectDuplicates
        run: nuget restore DetectDuplicates.sln
  
      - name: Build Solution
        working-directory: DetectDuplicates
        run: msbuild DetectDuplicates.sln -t:rebuild -property:Configuration=Debug
    
      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version 3.16.3 -DirectDownload -OutputDirectory .
            
      - name: Run UnitTests
        run: ./NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe  .\DetectDuplicates\DetectDuplicates.Lib.Tests\bin\Debug\net4.8\DetectDuplicates.Lib.Tests.dll
